clorg.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=256m
android.useAndroidX=true
android.newDsl=false
org.gradle.daemon=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
